### ISSUE TITLE
User cannot find the sites in Uploader app in project Tanah Papua Bio-acoustic Monitoring - WWF

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-uploader#190]
Original post: Help Scout #791

**Description**

User cannot find sites in the project (Tanah Papua Bioacoustic...) when trying to upload files from Uploader app.
(only 1 site (P3PB9-TJ) is visible)

Link to project https://arbimon.rfcx.org/project/wwf-tanah-papua-bio-acoustic-monitoring/audiodata/sites?site=21606

![Image](https://user-images.githubusercontent.com/87486094/237714382-1b3eddb2-8d5a-4769-aa5d-65b002589df0.png)

**Comment by rassokhina-e** [comment]
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/306e2d15-76df-45b0-9ec5-d2f907a75aed)
