### ISSUE TITLE
Fix timestamps - Reupload files showed duplicates on Uploader

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-uploader#194]
Original post: Help Scout#850

**Description**
After reupload files user got this status in Uploader "duplicate file. Matching SHA-1 signature already ingested."

Project: https://arbimon.rfcx.org/project/proyecto-mara-on/dashboard

Site names that user had the issue

- L01BPS58 (o9oml4e0awt9)
- L01MPS70 (plixlmbdfkzc)
- L01MPS75 (xwkaefmsql5t)
- L02BPS56 (m05h6cxp9acv)
- L01BPS69 (n0tlkzbbf6wl)
- L01BPS77 (2435te8xtwwe)
- L01SPS80 (6gp3zaezyrxq)
- L01MPS79 (ohhvqodwr52c)
- L01BPS57 (l15nmvxfqtyd)

![Image](https://user-images.githubusercontent.com/87486094/261931731-8f7e9f6b-8edd-4565-9a13-d6a7eccb50ad.png)

**Comment by koonchaya** [comment]
Example files
https://drive.google.com/file/d/1bi7-1nxXCuMAr4oX4QlAjXZjZdAvU37v/view?ts=64e3930b

**Comment by rassokhina-e** [comment]
I haven't the access to this folder

**Comment by koonchaya** [comment]
L01BPS58 (o9oml4e0awt9)
2023/03/03 12 20230302_202000.WAV 20230303_143500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01MPS70 (plixlmbdfkzc)
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 133 20230308_200500.WAV 20230309_185500.WAV

L01MPS75 (xwkaefmsql5t)
2023/03/06 228 20230306_010000.WAV 20230306_195500.WAV
2023/03/07 228 20230307_010000.WAV 20230307_195500.WAV
2023/03/08 228 20230308_010000.WAV 20230308_195500.WAV

L02BPS56 (m05h6cxp9acv)
2023/03/05 41 20230305_153500.WAV 20230305_185500.WAV
2023/03/06 288 20230305_190000.WAV 20230306_185500.WAV
2023/03/07 288 20230306_190000.WAV 20230307_185500.WAV
2023/03/08 288 20230307_190000.WAV 20230308_185500.WAV
2023/03/09 288 20230308_190000.WAV 20230309_185500.WAV

L01BPS69 (n0tlkzbbf6wl)
2023/03/02 87 20230302_114500.WAV 20230302_185500.WAV
2023/03/03 276 20230302_200000.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01BPS77 (2435te8xtwwe)
2023/03/02 45 20230302_151500.WAV 20230302_185500.WAV
2023/03/03 276 20230302_200000.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01SPS80 (6gp3zaezyrxq)
2023/03/03 33 20230303_161500.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01MPS79 (ohhvqodwr52c)
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01BPS57 (l15nmvxfqtyd)
2023/03/02 34 20230302_161048.WAV 20230302_185500.WAV
2023/03/03 276 20230302_200000.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

**Comment by koonchaya** [comment]
Delete files from 

L02BPS56 (m05h6cxp9acv)
2023/03/05 41 20230305_153500.WAV 20230305_185500.WAV
2023/03/06 288 20230305_190000.WAV 20230306_185500.WAV
2023/03/07 288 20230306_190000.WAV 20230307_185500.WAV
2023/03/08 288 20230307_190000.WAV 20230308_185500.WAV
2023/03/09 288 20230308_190000.WAV 20230309_185500.WAV

User can reupload this site because this site timezone is UTC-5

**Comment by koonchaya** [comment]
@rassokhin-s Please fix timestamps in these following sites by -1 hour

L01BPS58 (o9oml4e0awt9)
2023/03/03 12 20230302_202000.WAV 20230303_143500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01MPS70 (plixlmbdfkzc)
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 133 20230308_200500.WAV 20230309_185500.WAV

L01MPS75 (xwkaefmsql5t)
2023/03/06 228 20230306_010000.WAV 20230306_195500.WAV
2023/03/07 228 20230307_010000.WAV 20230307_195500.WAV
2023/03/08 228 20230308_010000.WAV 20230308_195500.WAV

L01BPS69 (n0tlkzbbf6wl)
2023/03/02 87 20230302_114500.WAV 20230302_185500.WAV
2023/03/03 276 20230302_200000.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01BPS77 (2435te8xtwwe)
2023/03/02 45 20230302_151500.WAV 20230302_185500.WAV
2023/03/03 276 20230302_200000.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01SPS80 (6gp3zaezyrxq)
2023/03/03 33 20230303_161500.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01MPS79 (ohhvqodwr52c)
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01BPS57 (l15nmvxfqtyd)
2023/03/02 34 20230302_161048.WAV 20230302_185500.WAV
2023/03/03 276 20230302_200000.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

**Comment by rassokhin-s** [comment]
hi @koonchaya , I have some questions:
```
L01BPS58 (o9oml4e0awt9)
2023/03/03 12 20230302_202000.WAV 20230303_143500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV
```

1) What is 12 and 276?
2) What time range should I apply: from 20230303_143500 to 20230308_200000 or for each of specified days I should use only specified time range?

**Comment by koonchaya** [comment]
@rassokhin-s 
- What is 12 and 276?
>>>It is the number of corrupted files

- What time range should I apply: from 20230303_143500 to 20230308_200000 or for each of specified days I should use only specified time range?
>>>20230303_143500 to 20230308_200000 This refer to filename. But please change the timestamps for the whole site.

**Comment by rassokhin-s** [comment]
L01BPS58 (o9oml4e0awt9) in progress
L01MPS70 (plixlmbdfkzc)
L01MPS75 (xwkaefmsql5t)
L01BPS69 (n0tlkzbbf6wl)
L01BPS77 (2435te8xtwwe)
L01SPS80 (6gp3zaezyrxq)
L01MPS79 (ohhvqodwr52c)
L01BPS57 (l15nmvxfqtyd)

**Comment by koonchaya** [comment]
L01MPS70 (plixlmbdfkzc) this looks correct? -  correct
L01MPS75 (xwkaefmsql5t) this looks correct? - correct

**Comment by rassokhin-s** [comment]
@koonchaya all sites are finished, please check
