### ISSUE TITLE
Prevent user to upload files with past and future timestamps

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-uploader#202]
User should not be able to upload files with 
- Future timestamps (after today's date should not be allowed)
- Past timestamps (earlier than 1971 should not be allowed)

This should apply to Arbimon Uploader and web uploader.

Error message for future and past timestamps to display on prepared tab
 - Future date upload: "Filename with future date is not permitted."
 - Past date upload: "Filename with date prior to 1971 is not permitted."
Design 
![image](https://github.com/rfcx/arbimon-uploader/assets/87486094/801a116f-7392-4d37-8c58-ef7e65efc443)

This should be done in the next sprint (Feb 8-22)

**Comment by koonchaya** [comment]
Do we need the core team update this on the ingest service? Need to discuss on EC Feb 12.

**Comment by rassokhina-e** [comment]
<img width="1000" alt="Untitled" src="https://github.com/rfcx/arbimon-uploader/assets/31901584/3f41fdaf-0275-4cab-a491-2331cda31c92">

**Comment by rassokhina-e** [comment]
<img width="980" alt="Untitled" src="https://github.com/rfcx/arbimon-uploader/assets/31901584/a7c3d781-77d3-439c-ace9-182b58f3f5a0">

**Comment by rassokhina-e** [comment]
>Do we need the core team update this on the ingest service? Need to discuss on EC Feb 12.

>=> Task created https://github.com/rfcx/ingest-service/issues/68. Frongs will be working on it

@koonchaya we can simply manage these 2 cases on the uploader side, also the requirement shows us the prepare tab error messages, so on this tab we haven't send the file to the ingest service side

**Comment by koonchaya** [comment]
Frongs already implemented to prevent these cases. Good to have both :)

**Comment by koonchaya** [comment]
Will this work for both iOS and window? @rassokhina-e
