### ISSUE TITLE
Update color theme & logo

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon-uploader#203]
Goal: update the Uploader branding to match the February arbimon.org launch

Suggested changes:
- All logos to new Arbimon logo (inside the app and the app icon)
- Poppins font everywhere (avoid using ABCFavorit because it might cause sizing issues)
- New color scheme matching arbimon.org

Notes:
- Avoid changes that will affect layout

**Comment by koonchaya** [comment]
- [ ] Update RFCx logo to Arbimon on Arbimon uploader icon to one of these icons https://drive.google.com/drive/folders/1k6_EvPjTnFpDqdCyfWeTtC3n_ANuvr1f?usp=sharing
