### ISSUE TITLE
Block user to upload big file

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon-uploader#204]
Related to: [Ingest Service POST /uploads receives duration and file_size to prevent a very long audio file](https://github.com/rfcx/ingest-service/issues/69)

- [ ] Send along `duration` and `file_size` in POST `/uploads` request

Error handling
- [ ] Do not retry the upload if
  - get the following errors from upload API (POST `/uploads`)
      ```
      ValidationError('Audio duration is more than 1 hour')
      -- OR --
      ValidationError(`This xxx file size is exceeding our limit (${flacLimitSize / 1_000_000}MB)`) 
       ```
  - get the following errors from check status API (GET `/uploads/:id`)
    ``` 
    Status code: 30
    Message: Audio duration is more than 1 hour
    -- OR -- 
    Status code: 30
    Message: This xxx file size is exceeding our limit ...
    ```

Frontend
![image](https://github.com/rfcx/arbimon-uploader/assets/87486094/1cbefcd1-9485-42f4-8be5-49333bf698fb)

Display the error message on prepared tab "Audio duration is longer than 1 hour. Please split files into shorter durations.”

**Comment by koonchaya** [comment]
@rassokhina-e Can we make sure when the user upload file with the duration >1 hour, we stop the file not to go back to queue a few times.

**Comment by rassokhina-e** [comment]
<img width="801" alt="Untitled" src="https://github.com/rfcx/arbimon-uploader/assets/31901584/cabf19e5-c5c6-40d1-b08a-35524f43dfde">

**Comment by rassokhina-e** [comment]
grafana log:
```
Body: {"filename":"2024-01-20 14.38.49 (1).wav","checksum":"23ca336f2f629dd3897b03a5f5f3ec7ec44ff75d","stream":"0hk0i4w59qig","timestamp":"2024-01-20T20:38:49.000Z","duration":211.289833,"file_size":30504212} {"meta":{}}
```

**Comment by rassokhina-e** [comment]
<img width="1004" alt="Untitled" src="https://github.com/rfcx/arbimon-uploader/assets/31901584/ba622a78-f9ac-4c9b-a115-9062631ef15e">

**Comment by koonchaya** [comment]
@rassokhina-e Blocking large file did not show the error message in the version you shared with me https://rfcx.slack.com/files/U73MLD3UP/F06LKAY44BZ/arbimon_uploader-1.5.6.dmg. 

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/1726205d-6335-402e-b817-c4d182c42b9c)

**Comment by koonchaya** [comment]
![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/c3fcb0ce-0d56-411c-8e6e-666c510ad0a8)
