### ISSUE TITLE
Check that Uploader CD is successful (for Windows build)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon-uploader#206]
Context: the big risk on the Uploader tasks is that we often encounter issues building the Windows version.

Steps:
- run the CD on the commit of the last release
- check the CD runs successfully
- check that the Windows build is working

**Comment by koonchaya** [comment]
There is other spots that still show RFCx icon (see screen recording) 

https://github.com/rfcx/arbimon-uploader/assets/87486094/fca08ba0-b578-426b-a3e2-20f2da3958b7

**Comment by koonchaya** [comment]
I still see the rfcx icon 

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/037f77a8-65c9-4c07-9902-9b174ab65ba4)
