### ISSUE TITLE
Uploader - block upload files to 0,0 site

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-uploader#208]
Original discussion https://rfcx.slack.com/archives/C02G4AR2GEL/p1709896671142039

I can create a 0,0 site from Site page (Site 5 and Site 8 -web created from the screenshot). The way we got blocked to upload files is the import button was disable.

<img width="1512" alt="Screenshot 2567-03-11 at 23 03 44 (1)" src="https://github.com/rfcx/arbimon-uploader/assets/9149523/f5adeaba-d96c-4920-aaff-463997654ef9">

**Comment by rassokhina-e** [comment]
<img width="1046" alt="Untitled" src="https://github.com/rfcx/arbimon-uploader/assets/31901584/7f19a22f-a214-4adf-be06-8ea435351d86">

**Comment by rassokhina-e** [comment]
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/1ef0de0c-1eae-462e-ad28-de04da18bba0)

**Comment by koonchaya** [comment]
I am confirming about how to display the site created without coordinates.
