### ISSUE TITLE
Change colors to support higher contrast

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon-uploader#209]
![Image](https://github.com/rfcx/arbimon/assets/9149523/cfe60061-cc35-4ee6-89ec-8ba01a0ba782)

- [ ] change 'util-gray-02' and anywhere else that is using `#7F7D78` to be `#A1A19E`
- [ ] change 'ibis' and anywhere else that is using `#CC1E3D` to be `#A31A33`
- [ ] change 'palm' and anywhere else that is using `#00AF90` to be `#00543B`

**Comment by rassokhina-e** [comment]
<img width="511" alt="Untitled" src="https://github.com/rfcx/arbimon-uploader/assets/31901584/ba1a540b-c1e4-4e76-89d6-504a40c83456">

**Comment by naluinui** [comment]
@rassokhina-e do you have any screenshot of where ibis & palm are used in Uploader. Just want to make sure it's pairing with the right color

**Comment by rassokhina-e** [comment]
the `ibis` color we used in 1.5.6 release for the warning messages and input borders in the warning state

@naluinui

**Comment by naluinui** [comment]
@koonchaya @rassokhina-e Can we close this task?
